backend:
  name: github
  repo: Wilto/wilto-makes-food # Path to your GitHub repository
  branch: v2
media_folder: "_src/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img"

media_library:
  name: cloudinary
  config:
    cloud_name: wilto
    api_key: 536243896247346

collections:
  - name: "recipes" # Used in routes, e.g., /admin/collections/blog
    label: "Recipes" # Used in the UI
    folder: "_src/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Permalink", name: "permalink", widget: "string", required: false }
      - {label: "Date", name: "date", widget: "date", default: 'Last Modified', format: 'YYYY-MM-DD' }
      - {label: "layout", name: "layout", widget: "select", options: [{ label: "V2", value: "layouts/v2-recipe.njk" }], default: "layouts/v2.njk", required: false }
      - {label: "Feature", name: "feat", widget: "boolean", default: false }
      - {label: "Type", name: "type", widget: "hidden", default: "recipe"}
      - {label: "Tags", name: "tags", widget: "list", required: false }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Lede", name: "lede", widget: "markdown", required: false}
      - label: "Featured Image"
        name: "feat_img"
        widget: "object"
        fields:
        - {label: "Image", name: "img", widget: "image", required: false }
        - {label: "alt", name: "alt", widget: "string", required: false}
        - {label: "Caption", name: "capt", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Related", name: "related", required: false,  multiple: true, widget: "relation", collection: "articles", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
      - {label: "Recipe Subhed", name: "subhed", widget: "string", required: false}
      - {label: "Recipe Notes", name: "notes", widget: "markdown", required: false}
      - label: "Recipe Meta"
        name: "meta"
        widget: "object"
        fields:
        - {label: "Active Time", name: "active", widget: "string", required: false}
        - {label: "Total Time", name: "total", widget: "string", required: false}
        - {label: "Serves", name: "serves", widget: "string", required: false}
      - label: "Ingredient Steps"
        name: "ingredient_steps"
        widget: "list"
        summary: '{{fields.title}}'
        required: false
        fields:
          - {label: "Title", name: "title", widget : "string", required: false }
          - label: "Ingredients"
            name: "ingredients"
            widget: "list"
            summary: '{{fields.amt_whole}}{{fields.amt_frac}} {{fields.measure}} {{fields.name}}'
            fields:
              - {label: Amount (whole), name: amt_whole, widget: string, required: false }
              - {label: Amount (fraction), name: amt_frac, widget: string, required: false }
              - {label: Measure, name: measure, widget: string, required: false }
              - {label: Ingredient, name: name, widget: string, required: false }
              - {label: Note, name: notes, widget: string, required: false }
              - {label: Note URL, name: notehref, widget: string, required: false }
              - {label: Optional, name: optional, widget: boolean, default: false }
      - label: "Instruction Steps"
        name: "instruction_steps"
        widget: "list"
        required: false
        summary: '{{fields.title}}'
        fields:
          - {label: Step, name: title, widget: "string", required: false }
          - label: "Instructions"
            name: "instructions"
            widget: "list"
            summary: '{{fields.instruction}}'
            fields:
              - {label: Instruction, name: instruction, widget: markdown }

  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "_src/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "layout", name: "layout", widget: "select", options: [{ label: "V2", value: "layouts/v2-article.njk" }], default: "layouts/v2.njk", required: false }
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subhed", name: "subhed", widget: "markdown"}
      - {label: "Lede", name: "lede", widget: "markdown"}
      - label: "Featured Image"
        name: "feat_img"
        widget: "object"
        fields:
        - {label: "Image", name: "img", widget: "image"}
        - {label: "alt", name: "alt", widget: "string"}
        - {label: "Caption", name: "capt", widget: "markdown"}
      - {label: "Related", name: "related", required: false, multiple: true, widget: "relation", collection: "recipes", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
      - {label: "Body", name: "body", widget: "markdown"}